# Generated by Django 5.1.3 on 2025-11-18 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalezaContribuyente',
            fields=[
                ('naturaleza_del_contribuyente', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('empleados', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('moneda', models.CharField(max_length=3)),
                ('sis_de_imp', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=253)),
                ('contraseña', models.CharField(max_length=15)),
                ('rol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id_contribuyente', models.AutoField(primary_key=True, serialize=False)),
                ('situación', models.CharField(max_length=20)),
                ('naturaleza_del_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.naturalezacontribuyente')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionTributaria',
            fields=[
                ('id_clasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_de_tributo', models.CharField(max_length=15)),
                ('monto', models.IntegerField()),
                ('actividad_economica', models.CharField(max_length=200)),
                ('codigo_CIIU', models.IntegerField()),
                ('regimen', models.TextField()),
                ('categoria', models.CharField(max_length=40)),
                ('fecha_de_creacion', models.DateField()),
                ('id_contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.contribuyente')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.pais')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.usuario')),
            ],
        ),
    ]
