# Generated by Django 5.1.3 on 2025-11-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='pais_nom',
            field=models.CharField(default='sin_nombre', max_length=15),
            preserve_default=False,
        ),
    ]
