# Generated by Django 5.1.3 on 2025-11-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_pais_pais_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.CharField(max_length=25),
        ),
    ]
