# Generated by Django 5.1.3 on 2025-11-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_usuario_date_joined_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=15),
        ),
    ]
