# Generated by Django 5.1.3 on 2025-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_remove_usuario_date_joined_remove_usuario_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=12),
        ),
    ]
