# Generated by Django 5.1.3 on 2025-11-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_pais_initial_data'),
        ('miapp', '0008_tributario'),
    ]

    operations = [
    ]
