# Generated by Django 5.1.3 on 2025-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_tributario_structure'),
        ('miapp', '0009_merge_0007_pais_initial_data_0008_tributario'),
    ]

    operations = [
    ]
