# Generated by Django 5.1.3 on 2025-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_merge_20251125_1412'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tributario',
        ),
    ]
