# Generated by Django 5.1.3 on 2025-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_delete_tributario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificaciontributaria',
            name='actividad_economica',
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='actividad_economica',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='nombre_comercial',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
