# Generated by Django 5.1.3 on 2025-11-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_remove_clasificaciontributaria_actividad_economica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='identificador_tributario',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='tipo_de_tributo',
            field=models.CharField(choices=[('IVA', 'IVA / IGV / IVA Colombia'), ('IR', 'Impuesto a la renta'), ('RET', 'Retenciones'), ('CO', 'Contribuciones obligatorias')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='actividad_economica',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='naturaleza_del_contribuyente',
            field=models.CharField(choices=[('PN', 'Persona natural'), ('PJ', 'Persona jurídica'), ('MP', 'Microempresa / PyME'), ('GC', 'Gran contribuyente'), ('NR', 'No domiciliado / no residente')], max_length=2),
        ),
    ]
