# Generated by Django 5.1.3 on 2025-11-26 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_contribuyente_identificador_tributario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='actividad_economica',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='identificador_tributario',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='nombre_comercial',
        ),
        migrations.RemoveField(
            model_name='contribuyente',
            name='tipo_de_tributo',
        ),
        migrations.AlterField(
            model_name='contribuyente',
            name='naturaleza_del_contribuyente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.naturalezacontribuyente'),
        ),
    ]
