# Generated by Django 5.1.3 on 2025-11-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_remove_contribuyente_actividad_economica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribuyente',
            name='actividad_economica',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='identificador_tributario',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='nombre_comercial',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
