# Generated by Django 5.1.3 on 2025-11-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0015_contribuyente_actividad_economica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.JSONField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
