# Generated by Django 5.1.3 on 2025-11-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
