# Generated by Django 5.1.3 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0017_alter_evento_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribuyente',
            name='naturaleza_del_contribuyente',
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='empleados',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='tipo',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='NaturalezaContribuyente',
        ),
    ]
