# Generated by Django 5.1.3 on 2025-11-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0018_remove_contribuyente_naturaleza_del_contribuyente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificaciontributaria',
            name='categoria',
        ),
        migrations.AddField(
            model_name='contribuyente',
            name='categoria',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
